<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ML248P1" failures="3" tests="8" name="Rest API regression Test" time="15.714" errors="0" timestamp="15 Jan 2023 21:37:58 GMT">
  <testcase classname="com.qa.api.gorest.tests.CreateUserTest" name="createUserAPIPOSTTest" time="4.082">
    <failure type="java.lang.AssertionError" message="expected [201] but found [422]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [422]
at com.qa.api.gorest.tests.CreateUserTest.createUserAPIPOSTTest(CreateUserTest.java:39)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createUserAPIPOSTTest -->
  <testcase classname="com.qa.api.gorest.tests.CreateUserTest" name="createUserAPIPOSTTest" time="1.043">
    <failure type="java.lang.AssertionError" message="expected [201] but found [422]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [422]
at com.qa.api.gorest.tests.CreateUserTest.createUserAPIPOSTTest(CreateUserTest.java:39)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createUserAPIPOSTTest -->
  <testcase classname="com.qa.api.gorest.tests.GetImgurApiTest" name="GetAccountBlockedStatusTest" time="1.843"/>
  <testcase classname="com.qa.api.gorest.tests.GetImgurApiTest" name="GetAccountImageTest" time="0.332"/>
  <testcase classname="com.qa.api.gorest.tests.CreateUserTest" name="createUserAPIPOSTTest" time="1.042">
    <failure type="java.lang.AssertionError" message="expected [201] but found [422]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [422]
at com.qa.api.gorest.tests.CreateUserTest.createUserAPIPOSTTest(CreateUserTest.java:39)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- createUserAPIPOSTTest -->
  <testcase classname="com.qa.api.gorest.tests.GetImgurApiTest" name="uploadImagePostAPITest" time="4.363"/>
  <testcase classname="com.qa.api.gorest.tests.GetUserTest" name="getAllUserListApiTest" time="0.991"/>
  <testcase classname="com.qa.api.gorest.tests.GetUserTest" name="getUserWithQueryParamApiTest" time="0.985"/>
</testsuite> <!-- Rest API regression Test -->
